masters:
  hosts:
    master:
      ansible_host: {{MASTER_IP}}
      ansible_user: {{USER}}
  vars:
    USER: arquitetura
    NETWORK: '10.1.0.0/16'
    MASTER_IP: '10.1.3.205'
    PROXY_HOST: '0.0.0.0'
    PROXY_PORT: '8001'
    ACCEPTED_HOSTS: '*'

workers:
  hosts:
    worker1:
      ansible_host: 10.1.3.206
      ansible_user: {{USER}}
    worker2:
      ansible_host: 10.1.3.207
      ansible_user: {{USER}}
  vars:
    USER: arquitetura