masters:
  hosts:
    master:
      ansible_host: 192.168.1.115
      ansible_user: root
  vars:
    USER: root
    NETWORK: '192.168.0.0/16'
    MASTER_IP: '192.168.1.115'
    PROXY_HOST: '0.0.0.0'
    PROXY_PORT: '8001'
    ACCEPTED_HOSTS: '*'

workers:
  hosts:
    worker1:
      ansible_host: 192.168.1.116
      ansible_user: root
    worker2:
      ansible_host: 192.168.1.117
      ansible_user: root
  vars:
    USER: root
