- hosts: master
  become: yes
  tasks:
    - name: install dashboard
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml

    - name: initialize proxy --> change this settings. this example is only for educational purposes.
      shell: kubectl proxy --address='0.0.0.0' --port='8001' --accepted-hosts='*'

   - name: install git
     yum:
        name: git
        state: present

    - name: download ingress 
      become: yes
      become_user: centos
      shell: git clone https://github.com/nginxinc/kubernetes-ingress.git
      args:
        chdir: $HOME
        
    - name: install ingress 
      become: yes
      become_user: centos
      shell: make
      args:
        chdir: $HOME/kubernetes-ingress
