- hosts: master
  become: yes
  tasks:
    - name: install dashboard
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml

    - name: initialize proxy --> change this settings. this example is only for educational purposes.
      shell: kubectl proxy --address=${PROXY_HOST} --port=${PROXY_PORT} --accepted-hosts=${ACCEPTED_HOSTS}

   - name: install git
     yum:
        name: git
        state: present

    - name: download ingress 
      become: yes
      become_user: ${USER}
      shell: git clone https://github.com/nginxinc/kubernetes-ingress.git
      args:
        chdir: $HOME
        
    - name: install ingress 
      become: yes
      become_user: ${USER}
      shell: make
      args:
        chdir: $HOME/kubernetes-ingress
